BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public int CuisineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<CuisineRestaurant> JoinEntities { get; set;}
    public Cuisine()
    {
      this.JoinEntities = new HashSet<CuisineRestaurant>();
    }
  }
}

BestRestaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Controllers
{
  public class CuisineController : Controller
  {
    private readonly BestRestaurantsContext _db;
    public CuisineController(BestRestaurantsContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCuisine = _db.Cuisines
      .Include(cuisine => cuisine.JoinEntities)
      .ThenInclude(join => join.Restaurant)
      .FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }
    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
    var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
    return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteRestaurant(int joinId)
    {
      var joinEntry = _db.CuisineRestaurant.FirstOrDefault(entry => entry.CuisineRestaurantId == joinId);
      _db.CuisineRestaurant.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      var thisRestaurant = _db.Restaurants
      .Include(rest => rest.JoinEntities)
      .ThenInclude(join => join.Cuisine);
      return View(thisRestaurant.ToList());
      // return View(_db.CuisineRestaurant.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create (Restaurant restaurant, int CuisineId)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      if (CuisineId != 0)
      {
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisRestaurant = _db.Restaurants
      .Include(rest => rest.JoinEntities)
      .ThenInclude(join => join.Cuisine)
      .FirstOrDefault(rest => rest.RestaurantId == id);
      return View(thisRestaurant);
    }
    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants
      .Include(rest => rest.JoinEntities)
      .ThenInclude(join => join.Cuisine)
      .FirstOrDefault(rest => rest.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }
    [HttpPost]
    public ActionResult Edit(Restaurant restaurant, int CuisineId, int joinId)
    {
      if (CuisineId != 0)
      {
        var joinEntry = _db.CuisineRestaurant.FirstOrDefault(entry => entry.CuisineRestaurantId == joinId);
        _db.CuisineRestaurant.Remove(joinEntry);    
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId});
      }
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddCuisine(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }
    [HttpPost]
    public ActionResult AddCuisine(Restaurant restaurant, int CuisineId)
    {
      if (CuisineId != 0)
      {
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult DeleteCuisine(int joinId)
    {
      var joinEntry = _db.CuisineRestaurant.FirstOrDefault(entry => entry.CuisineRestaurantId == joinId);
      _db.CuisineRestaurant.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Views/Cuisine/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h4>Add a new cuisine</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new cuisine" />
}
<p>@Html.ActionLink("Show all cuisines", "Index")</p>

BestRestaurants/Views/Cuisine/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Are you sure you want to remove this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to cuisine list", "Index")

BestRestaurants/Views/Cuisine/Details.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurants.Models.Cuisine;

<h2>Cuisine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<ul>
@if (@Model.JoinEntities.Count == 0)
{
  <p>No restaurants with this cuisine! :(</p>
}
  <h4>restaurants with this cuisine: </h4>
  @foreach(var join in @Model.JoinEntities)
  {
    <li>@Html.ActionLink($"{join.Restaurant.Name}", "Details", "Restaurants", new {id = join.RestaurantId})
      @using (Html.BeginForm("DeleteRestaurant", "Cuisine"))
    {
      @Html.Hidden("joinId", @join.CuisineRestaurantId)
      <input type="submit" value="Delete" />
    }
    </li>
  }
</ul>
<p>@Html.ActionLink("Add Restaurant", "Create", "Restaurants")</p>
<p>@Html.ActionLink("Back to Cuisines", "Index")</p>
<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>

BestRestaurants/Views/Cuisine/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h2>Edit</h2>
<h4>Edit this cuisine: @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <input type='submit' value='Save'/>
}
<p>@Html.ActionLink("Back to Cuisines", "Index")</p>

BestRestaurants/Views/Cuisine/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Cuisine>;

<h1>Types of Cuisine:</h1>
  
@if (Model.Count == 0)
{
  <p>You haven't added anything yet</p>
}

@foreach (Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
}
<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>