BestRestaurants/Models/Restaurant.cs
using System;
using System.Collections.Generic;
namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string PhoneNumber { get; set; }
    public string Address { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
    public virtual ICollection<CuisineRestaurant> JoinEntities { get; }
    public virtual ICollection<Review> Reviews { get; set;}
    public Restaurant()
    {
      this.JoinEntities = new HashSet<CuisineRestaurant>();
      this.Reviews = new HashSet<Review>();
    }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      var thisRestaurant = _db.Restaurants
      .Include(rest => rest.JoinEntities)
      .ThenInclude(join => join.Cuisine);
      return View(thisRestaurant.ToList());
      // return View(_db.CuisineRestaurant.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create (Restaurant restaurant, int CuisineId)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      if (CuisineId != 0)
      {
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisRestaurant = _db.Restaurants
      .Include(rest => rest.JoinEntities)
      .ThenInclude(join => join.Cuisine)
      .FirstOrDefault(rest => rest.RestaurantId == id);
      return View(thisRestaurant);
    }
    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants
      .Include(rest => rest.JoinEntities)
      .ThenInclude(join => join.Cuisine)
      .FirstOrDefault(rest => rest.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }
    [HttpPost]
    public ActionResult Edit(Restaurant restaurant, int CuisineId, int joinId)
    {
      if (CuisineId != 0)
      {
        var joinEntry = _db.CuisineRestaurant.FirstOrDefault(entry => entry.CuisineRestaurantId == joinId);
        _db.CuisineRestaurant.Remove(joinEntry);    
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId});
      }
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddCuisine(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }
    [HttpPost]
    public ActionResult AddCuisine(Restaurant restaurant, int CuisineId)
    {
      if (CuisineId != 0)
      {
        _db.CuisineRestaurant.Add(new CuisineRestaurant() { CuisineId = CuisineId, RestaurantId = restaurant.RestaurantId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult DeleteCuisine(int joinId)
    {
      var joinEntry = _db.CuisineRestaurant.FirstOrDefault(entry => entry.CuisineRestaurantId == joinId);
      _db.CuisineRestaurant.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class ReviewController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public ReviewController(BestRestaurantsContext db)
    {
      _db = db;
    }
    public ActionResult Create()
    {
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Review review)
    {
      _db.Reviews.Add(review);
      _db.SaveChanges();
      return RedirectToAction("Index", "Restaurants");
    }
    public ActionResult Details(int id)
    {
      Review thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == id);
      return View(thisReview);
    }
    public ActionResult Edit(int id)
    {
      var thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == id);
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View(thisReview);
    }
    [HttpPost]
    public ActionResult Edit(Review review)
    {
      _db.Entry(review).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Restaurants");
    }
    public ActionResult Delete(int id)
    {
      var thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == id);
      _db.Reviews.Remove(thisReview);
      _db.SaveChanges();
      return RedirectToAction("Index", "Restaurants");
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == id);
      _db.Reviews.Remove(thisReview);
      _db.SaveChanges();
      return RedirectToAction("Index", "Restaurants");
    }
  }
}

BestRestaurants/Views/Restaurants/AddCuisine.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant
<h2>Add a cuisine</h2>
<h4>Add a cuisine to this restaurant: @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)
  @Html.Label("Select Cuisine")
  @Html.DropDownList("CuisineId")
  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to restaurant list", "Index")</p>

BestRestaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h4>Add a new Restaurant</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)
  @Html.LabelFor(model => model.PhoneNumber)
  @Html.TextBoxFor(model => model.PhoneNumber)

  @Html.Label("Select cuisine")
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Add new restaurant" class="btn btn-danger" />
}
<p>@Html.ActionLink("Show all restaurants", "Index")</p>

BestRestaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h2>Are you sure you want to remove this restaurant?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to restaurants", "Index")

BestRestaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}
@model BestRestaurants.Models.Restaurant

<h2>Restaurant Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3><br>
<h3>@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)</h3><br>
<h3>@Html.DisplayNameFor(model => model.PhoneNumber): @Html.DisplayFor(model => model.PhoneNumber)</h3><br>
<ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Cuisine.Name</li>
    @using (Html.BeginForm("DeleteCuisine", "Restaurants"))
    {
      @Html.Hidden("joinId", @join.CuisineRestaurantId)
      <input type="submit" value="Delete" />
    }
  }
</ul>
<hr />
@foreach (var review in @Model.Reviews)
{
  <li>Review: @review.Description</li>
  <li>User: @review.Name</li>
  <hr />
}
<p>@Html.ActionLink("Back to restaurant list", "Index")</p>
<p>@Html.ActionLink("Edit restaurant", "Edit", new { id = Model.RestaurantId})</p>
<p>@Html.ActionLink("Remove restaurant", "Delete", new {id = Model.RestaurantId})
<p>@Html.ActionLink("Add a cuisine", "AddCuisine", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Leave a review", "Create", "Review")

BestRestaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)
  @foreach (var join in Model.JoinEntities)
  {
      @Html.Hidden("joinId", @join.CuisineRestaurantId)
  }
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Address)
  @Html.EditorFor(model => model.Address)
  @Html.LabelFor(model => model.PhoneNumber)
  @Html.EditorFor(model => model.PhoneNumber)

  @Html.Label("Select Cuisine")
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to restaurant list", "Index")</p>

BestRestaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>;

<h1>Restaurant</h1>

@if (@Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
}

<ul>
@foreach (var restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}", "Details", new {id = restaurant.RestaurantId}) : 
    @foreach(var cuisine in restaurant.JoinEntities)
    { 
      if (cuisine.Cuisine.Name != null)
      {
        <text> @cuisine.Cuisine.Name |</text>   
      }
    }
    @* if a restaurant has no JoinEntities display the text *@
    @if (restaurant.JoinEntities.Count == 0)
    {
      <text>This restaurant has no cuisine listed</text>
    }
  </li>
}
</ul>
<p>@Html.ActionLink("Add new restaurant", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>